print("")
print("")
print("")
print("")
print(" Hi! I'm Mila 2.0")
name = input("What is your name")
print(f"wowwow {name} is my favorite name!! nice to meet you!")
color = input("What is your favorite color?")
print(f"ooooh {color} is cool i like yellow!")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
print ("")
city = input("Do you always want to live in seattle or not? Tell me what your dream city is!")
print(f"huh i didnt know you liked {city}!!")
vacation = input("what is your ideal vacation?")
print(f"ok ok {vacation}sounds litty!")
animal = input("what is your favorite animal???")
print(f"danggggg {animal}are tuff asllll")
print ("")
print ("")
print ("")
print ("based on everything you told me we are making a story!")
print ("")
print(f"in sunset {name} was skipping in {vacation} and just got a charlie in the chocolate factory gold ticket to move to {city}! {name} wakes up surrounded by fluffy {animal} and went all {animal} whisperer and bonded with them")

